[tool.poetry]
name = "raggy2"
version = "0.1.0"
description = "Raggy AI System"
authors = ["Raggy Team"]

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
